# Generated by Django 4.1.1 on 2022-10-23 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("duration", models.IntegerField(default=0)),
                ("url", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=300)),
                ("intensityArray", models.TextField(default="[]")),
                ("tags", models.ManyToManyField(blank=True, to="database.tag")),
            ],
        ),
        migrations.CreateModel(
            name="presetTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.IntegerField(default=50)),
                ("clampStart", models.IntegerField(default=0)),
                ("clampEnd", models.IntegerField(default=100)),
                (
                    "ambiencePreset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.preset",
                    ),
                ),
                (
                    "ambienceTrack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.track"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="preset",
            name="tracks",
            field=models.ManyToManyField(
                through="database.presetTrack", to="database.track"
            ),
        ),
    ]
